### ISSUE TITLE
should we compile on windows?

### ISSUE THREAD

**Issue by ghost** [EspressoCake/Self_Deletion_BOF#1]
you cannot imagine the list of errors showing when compiling on Mac.

same as most of BOFs on GitHub  compiled with mingw version superior to 8.0.1. I have got version 9

weird , any help?? thx

**Comment by EspressoCake** [comment]
Hi @fendi1989,

Generally, I would suggest doing the following:

1.  Install `Docker`, which for `Mac`, can be found here: [installation instructions](https://docs.docker.com/desktop/mac/install/)
2.  Create a new directory, for reference we'll name it `BOF_DEVELOPMENT_FOLDER`
3.  Create a new file, named `Dockerfile`, which will contain the following:
     ```sh
     FROM ubuntu:latest
     RUN  apt-get update && apt-get install git mingw-64 -y
     ```
4.  From inside that directory: `docker build -t bofdev .`
5.  Once built, `git clone https://github.com/EspressoCake/Self_Deletion_BOF.git` from within `BOF_DEVELOPMENT_FOLDER`
6.  From within  `BOF_DEVELOPMENT_FOLDER`: `docker run -v $(pwd):/root/ -it bofdev /bin/bash`
7.  Now that you have shared a `volume` with your `container`, you may `cd` into the `/root` filepath and locate the project, and run the `Makefile` from the `src` directory.  This will be reflected in your `Mac`'s local path to  `BOF_DEVELOPMENT_FOLDER`.

For further reference, a number of commands in management of containers for `Docker` can be found here:
[cheatsheet](https://gist.github.com/spyesx/10c6ee350d760651f1fdb805611fc8fd)

**Comment by ghost** [comment]
thx , ill do so then :)
